export enum ExpenseType {
  TRAVEL = 'TRAVEL',
  ACCOMMODATION = 'ACCOMMODATION',
  MEALS = 'MEALS',
  TRANSPORT = 'TRANSPORT',
  ENTERTAINMENT = 'ENTERTAINMENT',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  SOFTWARE_SUBSCRIPTION = 'SOFTWARE_SUBSCRIPTION',
  TRAINING = 'TRAINING',
  COMMUNICATION = 'COMMUNICATION',
  MILEAGE = 'MILEAGE',
  PARKING = 'PARKING',
  OTHER = 'OTHER',
}

export enum PolicyRuleType {
  MAX_AMOUNT = 'MAX_AMOUNT',
  REQUIRES_RECEIPT = 'REQUIRES_RECEIPT',
  REQUIRES_APPROVAL = 'REQUIRES_APPROVAL',
  MULTI_LEVEL_APPROVAL = 'MULTI_LEVEL_APPROVAL',
  RECEIPT_THRESHOLD = 'RECEIPT_THRESHOLD',
  DAILY_LIMIT = 'DAILY_LIMIT',
  MONTHLY_LIMIT = 'MONTHLY_LIMIT',
}

export enum PolicyScope {
  GLOBAL = 'GLOBAL',
  DEPARTMENT = 'DEPARTMENT',
  ROLE = 'ROLE',
  PROJECT = 'PROJECT',
  INDIVIDUAL = 'INDIVIDUAL',
}
