version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tribecore_postgres
    environment:
      POSTGRES_DB: tribecore
      POSTGRES_USER: tribecore_user
      POSTGRES_PASSWORD: tribecore_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tribecore_network

  redis:
    image: redis:7-alpine
    container_name: tribecore_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tribecore_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tribecore_backend
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: tribecore
      DATABASE_USER: tribecore_user
      DATABASE_PASSWORD: tribecore_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-jwt-secret-change-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - tribecore_network
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tribecore_frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tribecore_network
    command: npm run dev -- --host

volumes:
  postgres_data:
  redis_data:

networks:
  tribecore_network:
    driver: bridge
