import { Entity, Column, Index, ManyToOne, JoinColumn } from 'typeorm';
import { BaseEntity } from '../../../common/entities/base.entity';
import { Organization } from '../../organization/entities/organization.entity';

export enum ReportType {
  BOARD_REPORT = 'BOARD_REPORT',
  ESG_REPORT = 'ESG_REPORT',
  ANNUAL_HC_REPORT = 'ANNUAL_HC_REPORT',
  QUARTERLY_REVIEW = 'QUARTERLY_REVIEW',
  CUSTOM = 'CUSTOM',
}

export enum ReportStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

/**
 * Human Capital Report Entity
 * Pre-built ISO 30414 reports for board/ESG
 */
@Entity('hc_reports')
@Index(['organizationId', 'reportType', 'periodStart'])
export class HCReport extends BaseEntity {
  @Column()
  @Index()
  organizationId: string;

  @ManyToOne(() => Organization)
  @JoinColumn({ name: 'organizationId' })
  organization: Organization;

  // Report identification
  @Column({ unique: true })
  reportId: string; // HCR-2025-Q1-001

  @Column()
  title: string;

  @Column({
    type: 'enum',
    enum: ReportType,
  })
  @Index()
  reportType: ReportType;

  @Column({
    type: 'enum',
    enum: ReportStatus,
    default: ReportStatus.DRAFT,
  })
  @Index()
  status: ReportStatus;

  // Period
  @Column({ type: 'date' })
  @Index()
  periodStart: Date;

  @Column({ type: 'date' })
  periodEnd: Date;

  @Column({ nullable: true })
  fiscalYear?: string;

  // Content
  @Column({ type: 'jsonb' })
  metrics: {
    metricId: string;
    metricCode: string;
    metricName: string;
    category: string;
    value: any;
    unit: string;
    previousValue?: any;
    changePercent?: number;
    benchmark?: number;
    target?: number;
    commentary?: string;
  }[];

  @Column({ type: 'text', nullable: true })
  executiveSummary?: string;

  @Column({ type: 'jsonb', nullable: true })
  keyFindings?: string[];

  @Column({ type: 'jsonb', nullable: true })
  recommendations?: string[];

  @Column({ type: 'jsonb', nullable: true })
  charts?: {
    chartType: string;
    title: string;
    data: any;
    config?: any;
  }[];

  // Generation
  @Column()
  generatedBy: string;

  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  generatedAt: Date;

  @Column({ default: false })
  autoGenerated: boolean;

  // Approval workflow
  @Column({ nullable: true })
  reviewedBy?: string;

  @Column({ type: 'timestamp', nullable: true })
  reviewedAt?: Date;

  @Column({ nullable: true })
  approvedBy?: string;

  @Column({ type: 'timestamp', nullable: true })
  approvedAt?: Date;

  @Column({ type: 'text', nullable: true })
  approvalNotes?: string;

  // Publishing
  @Column({ type: 'timestamp', nullable: true })
  publishedAt?: Date;

  @Column({ nullable: true })
  publishedTo?: string; // 'BOARD', 'PUBLIC', 'INTERNAL'

  @Column({ nullable: true })
  externalUrl?: string; // Link to published report

  @Column({ nullable: true })
  pdfUrl?: string; // Generated PDF

  // Version control
  @Column({ type: 'int', default: 1 })
  version: number;

  @Column({ nullable: true })
  previousVersionId?: string;

  // Metadata
  @Column({ type: 'jsonb', nullable: true })
  metadata?: Record<string, any>;
}
