export const UK_MANDATORY_TRAINING_COURSES = [
  {
    title: 'Health and Safety Awareness',
    description: 'Comprehensive training on workplace health and safety principles, covering emergency procedures, incident reporting (RIDDOR), and risk management.',
    category: 'STATUTORY',
    ukLegislation: ['Health and Safety at Work etc. Act 1974', 'Management of Health and Safety at Work Regulations 1999'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 90,
    applicableTo: ['All Employees', 'New Staff'],
    whatItCovers: 'Basic principles of workplace health and safety, emergency procedures, reporting incidents (RIDDOR), managing risks.',
    learningOutcomes: ['Understand HASAWA 1974', 'Recognize hazards', 'Report incidents', 'Emergency procedures'],
    requiresAssessment: true,
    minimumPassingScore: 80,
    requiresCertification: true,
  },
  {
    title: 'Fire Safety Awareness',
    description: 'Essential fire safety training covering prevention, hazard identification, evacuation procedures, and fire-fighting equipment.',
    category: 'STATUTORY',
    ukLegislation: ['Regulatory Reform (Fire Safety) Order 2005'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 60,
    applicableTo: ['All Employees'],
    whatItCovers: 'Fire prevention, hazard identification, evacuation procedures, fire-fighting equipment use.',
    learningOutcomes: ['Fire safety legislation', 'Recognize fire hazards', 'Evacuation procedures', 'Use fire equipment'],
    requiresAssessment: true,
    minimumPassingScore: 80,
    requiresCertification: true,
  },
  {
    title: 'Data Protection and UK GDPR',
    description: 'Comprehensive UK GDPR and Data Protection Act 2018 training for all employees handling personal data.',
    category: 'STATUTORY',
    ukLegislation: ['UK GDPR', 'Data Protection Act 2018'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 60,
    applicableTo: ['All Employees'],
    whatItCovers: '7 principles of data protection, securing data, handling breaches, subject rights.',
    learningOutcomes: ['UK GDPR principles', 'Data security', 'Breach management', 'ICO obligations'],
    requiresAssessment: true,
    minimumPassingScore: 85,
    requiresCertification: true,
  },
  {
    title: 'Equality, Diversity and Inclusion',
    description: 'Essential EDI training covering Equality Act 2010, protected characteristics, and preventing discrimination.',
    category: 'STATUTORY',
    ukLegislation: ['Equality Act 2010'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 60,
    applicableTo: ['All Employees'],
    whatItCovers: '9 protected characteristics, discrimination types, harassment prevention, inclusive practices.',
    learningOutcomes: ['Equality Act 2010', 'Protected characteristics', 'Prevent discrimination', 'Inclusive workplace'],
    requiresAssessment: true,
    minimumPassingScore: 80,
    requiresCertification: true,
  },
  {
    title: 'Display Screen Equipment Awareness',
    description: 'DSE training for employees using computers regularly. Covers ergonomic setup and health risks.',
    category: 'STATUTORY',
    ukLegislation: ['Health and Safety (Display Screen Equipment) Regulations 1992'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 30,
    applicableTo: ['DSE Users'],
    whatItCovers: 'Safe DSE use, ergonomic setup, health risks, breaks and posture, assessments.',
    learningOutcomes: ['DSE regulations', 'Ergonomic setup', 'Health risks', 'Self-assessments'],
    requiresAssessment: true,
    minimumPassingScore: 80,
    requiresCertification: true,
  },
  {
    title: 'Sexual Harassment Prevention',
    description: 'Mandatory training on preventing workplace sexual harassment. Required since October 2024.',
    category: 'STATUTORY',
    ukLegislation: ['Equality Act 2010', 'Worker Protection Act 2023'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 60,
    applicableTo: ['All Employees'],
    whatItCovers: 'Legal definition, unwanted conduct, reporting procedures, creating respectful culture.',
    learningOutcomes: ['Understand sexual harassment', 'Recognize forms', 'Reporting procedures', 'Respectful culture'],
    requiresAssessment: true,
    minimumPassingScore: 85,
    requiresCertification: true,
  },
  {
    title: 'Cyber Security Awareness',
    description: 'Essential cyber security training covering threats and data protection for UK GDPR compliance.',
    category: 'MANDATORY',
    ukLegislation: ['UK GDPR', 'Data Protection Act 2018'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 60,
    applicableTo: ['All Employees'],
    whatItCovers: 'Phishing, malware, password security, safe data handling, breach prevention.',
    learningOutcomes: ['Recognize threats', 'Password security', 'Secure data handling', 'Report incidents'],
    requiresAssessment: true,
    minimumPassingScore: 85,
    requiresCertification: true,
  },
  {
    title: 'First Aid at Work (FAW)',
    description: '3-day comprehensive first aid training for higher-risk workplaces. Valid for 3 years.',
    category: 'ROLE_SPECIFIC',
    ukLegislation: ['Health and Safety (First-Aid) Regulations 1981'],
    frequency: 'TRIENNIAL',
    validityMonths: 36,
    durationMinutes: 1440,
    applicableTo: ['Designated First Aiders'],
    whatItCovers: 'CPR, AED, choking, bleeding, shock, fractures, burns, medical emergencies.',
    learningOutcomes: ['CPR and AED', 'Control bleeding', 'Treat injuries', 'Medical emergencies'],
    requiresAssessment: true,
    minimumPassingScore: 100,
    requiresCertification: true,
  },
  {
    title: 'Manual Handling',
    description: 'Safe manual handling training covering lifting techniques and TILE risk assessment.',
    category: 'ROLE_SPECIFIC',
    ukLegislation: ['Manual Handling Operations Regulations 1992'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 120,
    applicableTo: ['Anyone involved in manual handling'],
    whatItCovers: 'Safe lifting, TILE assessment, handling aids, preventing MSDs.',
    learningOutcomes: ['TILE assessment', 'Safe techniques', 'Use handling aids', 'Prevent injuries'],
    requiresAssessment: true,
    minimumPassingScore: 80,
    requiresCertification: true,
  },
  {
    title: 'COSHH Training',
    description: 'Training for working with hazardous substances. Covers safe handling, storage, and disposal.',
    category: 'ROLE_SPECIFIC',
    ukLegislation: ['COSHH Regulations 2002'],
    frequency: 'ANNUAL',
    validityMonths: 12,
    durationMinutes: 120,
    applicableTo: ['Anyone working with hazardous substances'],
    whatItCovers: 'COSHH regulations, Safety Data Sheets, risk assessment, control measures, PPE.',
    learningOutcomes: ['COSHH regulations', 'Risk assessment', 'Control measures', 'Emergency procedures'],
    requiresAssessment: true,
    minimumPassingScore: 85,
    requiresCertification: true,
  },
  {
    title: 'Safeguarding',
    description: 'Mandatory training for staff working with children or vulnerable adults.',
    category: 'ROLE_SPECIFIC',
    ukLegislation: ['Children Act 1989', 'Care Act 2014'],
    frequency: 'BIENNIAL',
    validityMonths: 24,
    durationMinutes: 180,
    applicableTo: ['Staff working with children or vulnerable adults'],
    whatItCovers: 'Types of abuse, recognizing signs, reporting procedures, safeguarding principles.',
    learningOutcomes: ['Recognize abuse', 'Reporting procedures', 'Safeguarding principles', 'Support victims'],
    requiresAssessment: true,
    minimumPassingScore: 90,
    requiresCertification: true,
  },
];
